/* Fixtures shaped to the FastAPI responses (§12.2). The only place sample
 * data lives; swapping to the proxy means replacing client.ts, not this. */

import type { Course, Lecture, ModuleItem, Note, PillarProficiency, Topic, User } from './types'

export const ME: User = {
  id: 'u-1',
  name: 'Jean Kesselring',
  email: 'jean.kesselring@gmx.ch',
  role: 'educator',
  locale: 'en',
}

export const USERS: User[] = [
  ME,
  { id: 'u-2', name: 'Amara Okafor', email: 'amara@example.org', role: 'student', locale: 'en' },
  { id: 'u-3', name: 'Lukas Brandt', email: 'lukas@example.org', role: 'student', locale: 'de' },
  { id: 'u-4', name: 'Sena Yamamoto', email: 'sena@example.org', role: 'student', locale: 'en' },
  { id: 'u-5', name: 'Priya Raghunathan', email: 'priya@example.org', role: 'admin', locale: 'en' },
]

export const COURSES: Course[] = [
  {
    id: 'probability',
    title: 'Probability theory',
    educator: 'Dr M. Bauer',
    topicCount: 18,
    access: 'open',
    state: 'published',
    enrolled: true,
    mastery: 'in_progress',
    lastStudied: '2026-07-24',
    generatedAt: '2026-06-02',
  },
  {
    id: 'japanese-n5',
    title: 'Japanese N5',
    educator: 'Jean Kesselring',
    topicCount: 24,
    access: 'closed',
    state: 'published',
    enrolled: true,
    mastery: 'in_progress',
    lastStudied: '2026-07-26',
    generatedAt: '2026-07-11',
  },
  {
    id: 'geomorphology',
    title: 'Geomorphology',
    educator: 'Prof. A. Lindqvist',
    topicCount: 12,
    access: 'open',
    state: 'published',
    enrolled: false,
    mastery: 'unstarted',
    lastStudied: null,
    generatedAt: '2025-09-30', // stale — educators only (§13.6)
  },
  {
    id: 'thermodynamics',
    title: 'Thermodynamics',
    educator: 'Jean Kesselring',
    topicCount: 9,
    access: 'closed',
    state: 'draft',
    enrolled: false,
    mastery: 'unstarted',
    lastStudied: null,
    generatedAt: '2026-07-20',
  },
]

export const LECTURES: Lecture[] = [
  {
    id: 'l-1',
    courseId: 'probability',
    title: 'Foundations',
    topicIds: ['t-1', 't-2'],
    state: 'published',
  },
  {
    id: 'l-2',
    courseId: 'probability',
    title: 'Conditioning',
    topicIds: ['t-3', 't-4'],
    state: 'published',
  },
  {
    id: 'l-3',
    courseId: 'japanese-n5',
    title: 'Kana',
    topicIds: ['t-10', 't-11'],
    state: 'published',
  },
  { id: 'l-4', courseId: 'japanese-n5', title: 'Particles', topicIds: ['t-12'], state: 'draft' },
]

export const TOPICS: Topic[] = [
  {
    id: 't-1',
    courseId: 'probability',
    parentId: null,
    title: 'Sample spaces',
    blurb: 'The set of every outcome an experiment can produce.',
    mastery: 'mastered',
    progressPercent: 88,
    childIds: ['t-5', 't-7', 't-8'],
    moduleCount: 6,
    span: 2,
  },
  {
    id: 't-2',
    courseId: 'probability',
    parentId: null,
    title: 'Axioms',
    blurb: 'The three rules every probability measure obeys.',
    mastery: 'in_progress',
    progressPercent: 46,
    childIds: [],
    moduleCount: 4,
    span: 1,
  },
  {
    id: 't-3',
    courseId: 'probability',
    parentId: null,
    title: 'Conditional probability',
    blurb: 'How knowing one outcome changes the odds of another.',
    mastery: 'in_progress',
    progressPercent: 62,
    childIds: ['t-6', 't-9', 't-16'],
    moduleCount: 9,
    span: 3,
  },
  {
    id: 't-4',
    courseId: 'probability',
    parentId: null,
    title: 'Independence',
    blurb: 'When one event tells you nothing about another.',
    mastery: 'unstarted',
    progressPercent: 12,
    childIds: [],
    moduleCount: 5,
    span: 1,
  },
  {
    id: 't-5',
    courseId: 'probability',
    parentId: 't-1',
    title: 'Events',
    blurb: 'Subsets of the sample space.',
    mastery: 'mastered',
    progressPercent: 91,
    childIds: ['t-17', 't-18'],
    moduleCount: 3,
    span: 1,
  },
  {
    id: 't-6',
    courseId: 'probability',
    parentId: 't-3',
    title: "Bayes' theorem",
    blurb: 'Inverting a conditional.',
    mastery: 'in_progress',
    progressPercent: 58,
    childIds: ['t-24', 't-25'],
    moduleCount: 7,
    span: 2,
  },
  {
    id: 't-7',
    courseId: 'probability',
    parentId: 't-1',
    title: 'Random variables',
    blurb: 'Functions that turn outcomes into quantities.',
    mastery: 'in_progress',
    progressPercent: 43,
    childIds: ['t-19', 't-22', 't-23'],
    moduleCount: 8,
    span: 2,
  },
  {
    id: 't-8',
    courseId: 'probability',
    parentId: 't-1',
    title: 'Counting methods',
    blurb: 'Permutations and combinations for finite spaces.',
    mastery: 'unstarted',
    progressPercent: 8,
    childIds: [],
    moduleCount: 5,
    span: 1,
  },
  {
    id: 't-9',
    courseId: 'probability',
    parentId: 't-3',
    title: 'Conditional independence',
    blurb: 'Independence after conditioning on shared information.',
    mastery: 'unstarted',
    progressPercent: 18,
    childIds: [],
    moduleCount: 6,
    span: 2,
  },
  {
    id: 't-16',
    courseId: 'probability',
    parentId: 't-3',
    title: 'Law of total probability',
    blurb: 'Assembling a probability from a partition of cases.',
    mastery: 'mastered',
    progressPercent: 84,
    childIds: [],
    moduleCount: 4,
    span: 1,
  },
  {
    id: 't-17',
    courseId: 'probability',
    parentId: 't-5',
    title: 'Sigma-algebras',
    blurb: 'Event collections closed under the operations probability needs.',
    mastery: 'in_progress',
    progressPercent: 55,
    childIds: [],
    moduleCount: 5,
    span: 2,
  },
  {
    id: 't-18',
    courseId: 'probability',
    parentId: 't-5',
    title: 'Set operations',
    blurb: 'Unions, intersections, complements, and differences.',
    mastery: 'mastered',
    progressPercent: 94,
    childIds: [],
    moduleCount: 4,
    span: 1,
  },
  {
    id: 't-19',
    courseId: 'probability',
    parentId: 't-7',
    title: 'Discrete variables',
    blurb: 'Countable values described by probability masses.',
    mastery: 'mastered',
    progressPercent: 82,
    childIds: [],
    moduleCount: 6,
    span: 2,
  },
  {
    id: 't-22',
    courseId: 'probability',
    parentId: 't-7',
    title: 'Continuous variables',
    blurb: 'Ranges of values described by probability densities.',
    mastery: 'unstarted',
    progressPercent: 14,
    childIds: [],
    moduleCount: 7,
    span: 2,
  },
  {
    id: 't-23',
    courseId: 'probability',
    parentId: 't-7',
    title: 'Expectation',
    blurb: 'The probability-weighted centre of a random variable.',
    mastery: 'in_progress',
    progressPercent: 48,
    childIds: [],
    moduleCount: 5,
    span: 1,
  },
  {
    id: 't-24',
    courseId: 'probability',
    parentId: 't-6',
    title: 'Priors and likelihoods',
    blurb: 'The two inputs Bayes combines before seeing the evidence.',
    mastery: 'in_progress',
    progressPercent: 64,
    childIds: ['t-26'],
    moduleCount: 6,
    span: 2,
  },
  {
    id: 't-25',
    courseId: 'probability',
    parentId: 't-6',
    title: 'Evidence and posterior',
    blurb: 'Normalisation and the updated distribution after evidence.',
    mastery: 'unstarted',
    progressPercent: 22,
    childIds: [],
    moduleCount: 5,
    span: 2,
  },
  {
    id: 't-26',
    courseId: 'probability',
    parentId: 't-24',
    title: 'Likelihood ratios',
    blurb: 'How strongly an observation shifts competing hypotheses.',
    mastery: 'mastered',
    progressPercent: 89,
    childIds: [],
    moduleCount: 4,
    span: 1,
  },
  {
    id: 't-10',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'Hiragana',
    blurb: 'The 46 basic syllabary characters.',
    mastery: 'mastered',
    childIds: [],
    moduleCount: 12,
    span: 2,
  },
  {
    id: 't-11',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'Katakana',
    blurb: 'The syllabary used for loanwords.',
    mastery: 'in_progress',
    childIds: [],
    moduleCount: 10,
    span: 2,
  },
  {
    id: 't-12',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'The particle に',
    blurb: 'Direction, time, and indirect objects.',
    mastery: 'unstarted',
    childIds: [],
    moduleCount: 8,
    span: 1,
  },
  {
    id: 't-13',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'Kanji: nature',
    blurb: 'The characters for mountain, river, field and rain.',
    mastery: 'unstarted',
    childIds: [],
    moduleCount: 9,
    span: 2,
  },
  {
    id: 't-14',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'Everyday vocabulary',
    blurb: 'Words you need before you need grammar.',
    mastery: 'in_progress',
    childIds: [],
    moduleCount: 14,
    span: 2,
  },
  {
    id: 't-15',
    courseId: 'japanese-n5',
    parentId: null,
    title: 'Verb forms',
    blurb: 'Polite, plain, past and negative.',
    mastery: 'unstarted',
    childIds: [],
    moduleCount: 11,
    span: 3,
  },
  {
    id: 't-20',
    courseId: 'geomorphology',
    parentId: null,
    title: 'Mountain ranges',
    blurb: 'How plates build relief, and where.',
    mastery: 'in_progress',
    childIds: [],
    moduleCount: 7,
    span: 2,
  },
  {
    id: 't-21',
    courseId: 'geomorphology',
    parentId: null,
    title: 'Glacial landforms',
    blurb: 'What ice leaves behind when it retreats.',
    mastery: 'unstarted',
    childIds: [],
    moduleCount: 6,
    span: 2,
  },
  {
    id: 't-30',
    courseId: 'thermodynamics',
    parentId: null,
    title: 'Energy balance',
    blurb: 'In, out, and what is left stored.',
    mastery: 'unstarted',
    childIds: [],
    moduleCount: 5,
    span: 1,
  },
]

/* A session queue mixing graded and ungraded types, so the deck exercises
 * both shapes from §6.10 and every response control from §6.12. */
export const QUEUE: ModuleItem[] = [
  {
    id: 'm-1',
    topicId: 't-6',
    topicTitle: "Bayes' theorem",
    moduleType: 'flashcard',
    contentType: 'flashcard',
    prompt: 'State Bayes’ theorem.',
    answer: 'P(A|B) = P(B|A)·P(A) / P(B)',
  },
  {
    id: 'm-2',
    topicId: 't-3',
    topicTitle: 'Conditional probability',
    moduleType: 'quiz',
    contentType: 'quiz',
    prompt:
      'Two fair dice are rolled. Given that the sum is 8, what is the probability that one die shows 5?',
    options: ['1/5', '2/5', '1/6', '1/3'],
    answer: '2/5',
  },
  {
    id: 'm-3',
    topicId: 't-3',
    topicTitle: 'Conditional probability',
    moduleType: 'diagram_schematic',
    contentType: 'text',
    prompt: 'Partitioning a sample space',
    body:
      'A **partition** splits the sample space into disjoint events whose union is everything. ' +
      'The law of total probability sums the conditional probabilities across a partition, ' +
      'weighting each by how likely that part is.\n\n' +
      '- The parts are mutually exclusive\n- Their union is the whole space\n- Every part has non-zero probability',
    answer: '',
  },
  {
    id: 'm-4',
    topicId: 't-11',
    topicTitle: 'Katakana',
    moduleType: 'vocab_production',
    contentType: 'quiz',
    prompt: 'library',
    lang: 'ja',
    answer: 'としょかん',
    acceptedAnswers: ['図書館'],
  },
  {
    id: 'm-5',
    topicId: 't-12',
    topicTitle: 'The particle に',
    moduleType: 'particle_cloze',
    contentType: 'quiz',
    prompt: 'Complete the sentence.',
    lang: 'ja',
    clozeBefore: '学校',
    clozeAfter: '行きます。',
    bank: ['に', 'を', 'で', 'から'],
    answer: 'に',
  },
  {
    id: 'm-6',
    topicId: 't-10',
    topicTitle: 'Hiragana',
    moduleType: 'sentence_scramble',
    contentType: 'quiz',
    prompt: 'Rebuild the sentence: “I go to school every day.”',
    lang: 'ja',
    tokens: ['私は', '毎日', '学校に', '行きます'],
    answer: '私は|毎日|学校に|行きます',
  },
  {
    id: 'm-7',
    topicId: 't-10',
    topicTitle: 'Hiragana',
    moduleType: 'discrimination',
    contentType: 'quiz',
    prompt: 'Which character is “nu”?',
    lang: 'ja',
    options: ['ぬ', 'め'],
    answer: 'ぬ',
  },
  {
    id: 'm-8',
    topicId: 't-4',
    topicTitle: 'Independence',
    moduleType: 'stat_boxes',
    contentType: 'text',
    prompt: 'Independence at a glance',
    figure: {
      kind: 'stats',
      items: [
        { label: 'Mean', value: '3.5' },
        { label: 'Variance', value: '2.92' },
        { label: 'Outcomes', value: '6' },
        { label: 'P(even)', value: '0.5' },
      ],
    },
    answer: '',
  },
]

export const NOTES: Note[] = [
  {
    id: 'n-1',
    topicId: 't-6',
    topicTitle: "Bayes' theorem",
    courseId: 'probability',
    courseTitle: 'Probability theory',
    text: 'I keep inverting the conditional the wrong way round. Read the denominator first.',
    lang: 'en',
    kind: 'learner',
    state: 'published',
    createdAt: '2026-07-22',
  },
  {
    id: 'n-2',
    topicId: 't-12',
    topicTitle: 'The particle に',
    courseId: 'japanese-n5',
    courseTitle: 'Japanese N5',
    text: 'に marks arrival, で marks where an action happens. 学校に行く vs 学校で食べる.',
    lang: 'ja',
    kind: 'learner',
    state: 'published',
    createdAt: '2026-07-25',
  },
  {
    id: 'n-3',
    topicId: 't-3',
    topicTitle: 'Conditional probability',
    courseId: 'probability',
    courseTitle: 'Probability theory',
    text: 'Worth stressing that the sample space shrinks — that is the whole idea.',
    lang: 'en',
    kind: 'educator',
    state: 'published',
    createdAt: '2026-07-19',
  },
]

export const PILLARS: PillarProficiency[] = [
  { pillar: 'Facts', score: 0.82 },
  { pillar: 'Processes', score: 0.41 },
  { pillar: 'Concepts', score: 0.66 },
  { pillar: 'Applications', score: null }, // not begun — never a deficit (§11.7)
]
