/* The type table — design_system.md §6.14, widened to the whole catalogue.
 *
 * `graded` and `mode` mirror the backend's module_registry.py and are NOT
 * decided here (§3.2): the frontend reads the classification, it never
 * re-derives it. The last fields are the design system's own.
 *
 * Two rules generate almost all of this:
 *   Topic rule — hide the topic name exactly where the topic names the thing
 *   being recalled.
 *   Tolerance rule — exact where the written form IS the objective, tolerant
 *   where the answer is meaning in prose, n/a for non-text controls.
 *
 * Three rows changed when complete_modules.md was ruled the authority on
 * interaction (2026-07-28):
 *   · `conversion_calculator` is BACK. §6.10 deleted it; the catalogue lists
 *     it as a live interactive tool with a real input loop, so it returns as
 *     an ungraded type with its own response affordance.
 *   · `audio` and `video` are separate rows rather than a shared `media`,
 *     because the catalogue distinguishes their preload behaviour and their
 *     control sets, and ContentType already separates them.
 *   · `vocab_guess` responds by SPEECH, not by choice. The earlier row had it
 *     as a choice drill, which is not what `vocab_guess` does in JKG.
 */

export type PracticeMode = 'recognition' | 'production' | 'in_context'

export type ResponseControl =
  | 'none' // reveal + self-rate
  | 'choice'
  | 'text'
  | 'cloze'
  | 'ordering'
  | 'map'
  | 'handwriting'
  | 'speech'
  | 'scroll' // ungraded: no response control at all

export type Tolerance = 'exact' | 'tolerant' | 'na'

/** The six ContentTypes the frontend is allowed to reason about (§3.2). */
export type ContentType = 'summary' | 'text' | 'video' | 'audio' | 'flashcard' | 'quiz'

export interface ModuleTypeSpec {
  id: string
  mode: PracticeMode
  graded: boolean
  /** §6.14 topic rule. */
  showTopic: boolean
  tolerance: Tolerance
  response: ResponseControl
  contentType: ContentType
  /**
   * `lattice` removes the study-card material and lets the response blend
   * directly into the page field. Interaction and grading remain unchanged.
   */
  presentation?: 'frame' | 'lattice'
  /**
   * Ungraded only. The catalogue's "shared learning-card behaviour" gives
   * every learning card a reversible Hard/Easy; a few types (the interactive
   * ones) also carry their own controls, but the feed rating is universal.
   */
  feedRating?: boolean
  /** Marked ⚠ in §6.14 — a judgement call, not generated by the rules. */
  arguable?: boolean
}

const t = (s: ModuleTypeSpec) => s

/* ── Graded — academic (5) ─────────────────────────────────────────
 *
 * Sets are presentation data (`cards`), not a second flashcard type, and
 * MCQ is simply the long name of the ordinary choice quiz. Legacy IDs are
 * normalised at the bottom of this file so old stored sessions still open. */

const GRADED_ACADEMIC: ModuleTypeSpec[] = [
  t({
    id: 'flashcard',
    mode: 'recognition',
    graded: true,
    showTopic: false,
    tolerance: 'na',
    response: 'none',
    contentType: 'flashcard',
  }),
  t({
    id: 'quiz',
    mode: 'recognition',
    graded: true,
    showTopic: false,
    tolerance: 'na',
    response: 'choice',
    contentType: 'quiz',
  }),
  t({
    id: 'timeline_drag_exercise',
    mode: 'production',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'ordering',
    contentType: 'quiz',
  }),
  t({
    id: 'map_click_quiz',
    mode: 'production',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'map',
    contentType: 'quiz',
  }),
  t({
    id: 'lattice_map_click_quiz',
    mode: 'production',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'map',
    contentType: 'quiz',
    presentation: 'lattice',
  }),
]

/* ── Graded — language (12) ──────────────────────────────────────────
 * None of these exists in either registry yet (§12.1); mode and graded
 * here are this document's proposal until the rows land. */

const GRADED_LANGUAGE: ModuleTypeSpec[] = [
  t({
    id: 'discrimination',
    mode: 'recognition',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'choice',
    contentType: 'quiz',
  }),
  t({
    id: 'kanji_meaning',
    mode: 'recognition',
    graded: true,
    showTopic: false,
    tolerance: 'na',
    response: 'choice',
    contentType: 'quiz',
    arguable: true,
  }),
  t({
    id: 'kanji_reading',
    mode: 'production',
    graded: true,
    showTopic: false,
    tolerance: 'exact',
    response: 'text',
    contentType: 'quiz',
    arguable: true,
  }),
  t({
    id: 'vocab_recognition',
    mode: 'recognition',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'choice',
    contentType: 'quiz',
  }),
  t({
    id: 'vocab_production',
    mode: 'production',
    graded: true,
    showTopic: false,
    tolerance: 'exact',
    response: 'text',
    contentType: 'quiz',
  }),
  // Spoken production. The recogniser's kana interpretation is the answer;
  // typing it is the equivalent path where speech is unavailable (§9.3).
  t({
    id: 'vocab_guess',
    mode: 'production',
    graded: true,
    showTopic: true,
    tolerance: 'exact',
    response: 'speech',
    contentType: 'audio',
  }),
  // Topic names the exact form being tested — the leak §6.14 warns about.
  t({
    id: 'conjugation',
    mode: 'production',
    graded: true,
    showTopic: false,
    tolerance: 'exact',
    response: 'text',
    contentType: 'quiz',
  }),
  t({
    id: 'particle_cloze',
    mode: 'in_context',
    graded: true,
    showTopic: false,
    tolerance: 'exact',
    response: 'cloze',
    contentType: 'quiz',
  }),
  t({
    id: 'sentence_scramble',
    mode: 'in_context',
    graded: true,
    showTopic: true,
    tolerance: 'na',
    response: 'ordering',
    contentType: 'quiz',
  }),
  t({
    id: 'grammar_recognition',
    mode: 'recognition',
    graded: true,
    showTopic: false,
    tolerance: 'na',
    response: 'choice',
    contentType: 'quiz',
  }),
  t({
    id: 'transcription',
    mode: 'in_context',
    graded: true,
    showTopic: true,
    tolerance: 'exact',
    response: 'text',
    contentType: 'audio',
  }),
  t({
    id: 'kanji_writing',
    mode: 'production',
    graded: true,
    showTopic: false,
    tolerance: 'na',
    response: 'handwriting',
    contentType: 'quiz',
    arguable: true,
  }),
]

/* ── Ungraded — the learning cards (17) ──────────────────────────────
 * All in_context. All scroll rather than using the frame; all show the
 * topic, because nothing is being recalled and so nothing can be cued.
 * Every one carries the catalogue's reversible Hard/Easy. */

const UNGRADED_IDS: Array<[string, ContentType]> = [
  ['text', 'text'],
  ['summary', 'summary'],
  ['topic_card', 'summary'],
  ['diagram_schematic', 'text'],
  ['input_output_balance', 'text'],
  ['stat_boxes', 'text'],
  ['key_value_pairs', 'text'],
  ['timeline', 'text'],
  ['common_mistakes', 'text'],
  ['comparison_vs_similar', 'text'],
  ['conversion_calculator', 'text'],
  ['formula_equation', 'text'],
  ['hero_image', 'text'],
  ['globe_pin', 'text'],
  ['model_3d', 'video'],
  ['audio', 'audio'],
  ['video', 'video'],
]

const UNGRADED: ModuleTypeSpec[] = UNGRADED_IDS.map(([id, contentType]) =>
  t({
    id,
    mode: 'in_context',
    graded: false,
    showTopic: true,
    tolerance: 'na',
    response: 'scroll',
    contentType,
    feedRating: true,
  }),
)

export const MODULE_TYPES: ModuleTypeSpec[] = [...GRADED_ACADEMIC, ...GRADED_LANGUAGE, ...UNGRADED]

const BY_ID = new Map(MODULE_TYPES.map((m) => [m.id, m]))

/** Historical names accepted at the data boundary, never shown as modules. */
const ALIASES: Record<string, string> = {
  flashcard_set: 'flashcard',
  language_flashcard: 'flashcard',
  mcq: 'quiz',
  kana_recognition: 'quiz',
  // Removed from the repertoire. Existing stored attempts retain a usable
  // typed-production renderer until their content is migrated.
  kana_production: 'vocab_production',
}

export function moduleType(id: string): ModuleTypeSpec | undefined {
  return BY_ID.get(ALIASES[id] ?? id)
}

/* An unknown type must still render. The server can register a type this
 * build has never heard of, and the honest fallback is the ungraded scroll
 * shell: it shows whatever content arrived and asks nothing of the learner,
 * where a graded frame would offer a Check with nothing to mark. */
const FALLBACK: ModuleTypeSpec = t({
  id: 'text',
  mode: 'in_context',
  graded: false,
  showTopic: true,
  tolerance: 'na',
  response: 'scroll',
  contentType: 'text',
  feedRating: true,
})

export function moduleTypeOrDefault(id: string): ModuleTypeSpec {
  return BY_ID.get(ALIASES[id] ?? id) ?? FALLBACK
}

/** §3.2: the accent and its required second channel, keyed by ContentType. */
export const CONTENT_TYPE_LABEL: Record<ContentType, string> = {
  summary: 'Summary',
  text: 'Text',
  video: 'Video',
  audio: 'Audio',
  flashcard: 'Flashcard',
  quiz: 'Quiz',
}
