/* The type table — design_system.md §6.14.
 *
 * `graded` and `mode` mirror the backend's module_registry.py and are NOT
 * decided here (§3.2): the frontend reads the classification, it never
 * re-derives it. The last three fields are the design system's own.
 *
 * Two rules generate almost all of this:
 *   Topic rule — hide the topic name exactly where the topic names the thing
 *   being recalled.
 *   Tolerance rule — exact where the written form IS the objective, tolerant
 *   where the answer is meaning in prose, n/a for non-text controls.
 */

export type PracticeMode = 'recognition' | 'production' | 'in_context'

export type ResponseControl =
  | 'none' // reveal + self-rate
  | 'choice'
  | 'text'
  | 'cloze'
  | 'ordering'
  | 'map'
  | 'handwriting'
  | 'scroll' // ungraded: no response control at all

export type Tolerance = 'exact' | 'tolerant' | 'na'

/** The six ContentTypes the frontend is allowed to reason about (§3.2). */
export type ContentType =
  | 'summary'
  | 'text'
  | 'video'
  | 'audio'
  | 'flashcard'
  | 'quiz'

export interface ModuleTypeSpec {
  id: string
  mode: PracticeMode
  graded: boolean
  /** §6.14 topic rule. */
  showTopic: boolean
  tolerance: Tolerance
  response: ResponseControl
  contentType: ContentType
  /** Marked ⚠ in §6.14 — a judgement call, not generated by the rules. */
  arguable?: boolean
}

const t = (s: ModuleTypeSpec) => s

/* ── Graded — academic (6) ───────────────────────────────────────── */

const GRADED_ACADEMIC: ModuleTypeSpec[] = [
  t({ id: 'flashcard', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'none', contentType: 'flashcard' }),
  t({ id: 'flashcard_set', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'none', contentType: 'flashcard' }),
  t({ id: 'quiz', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'mcq', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'timeline_drag_exercise', mode: 'production', graded: true, showTopic: true, tolerance: 'na', response: 'ordering', contentType: 'quiz' }),
  t({ id: 'map_click_quiz', mode: 'production', graded: true, showTopic: true, tolerance: 'na', response: 'map', contentType: 'quiz' }),
]

/* ── Graded — language (15 + kanji_writing) ──────────────────────────
 * None of these exists in either registry yet (§12.1); mode and graded
 * here are this document's proposal until the rows land. */

const GRADED_LANGUAGE: ModuleTypeSpec[] = [
  t({ id: 'language_flashcard', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'none', contentType: 'flashcard' }),
  t({ id: 'kana_recognition', mode: 'recognition', graded: true, showTopic: true, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'kana_production', mode: 'production', graded: true, showTopic: true, tolerance: 'exact', response: 'text', contentType: 'quiz' }),
  t({ id: 'discrimination', mode: 'recognition', graded: true, showTopic: true, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'kanji_meaning', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'choice', contentType: 'quiz', arguable: true }),
  t({ id: 'kanji_reading', mode: 'production', graded: true, showTopic: false, tolerance: 'exact', response: 'text', contentType: 'quiz', arguable: true }),
  t({ id: 'vocab_recognition', mode: 'recognition', graded: true, showTopic: true, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'vocab_production', mode: 'production', graded: true, showTopic: true, tolerance: 'exact', response: 'text', contentType: 'quiz' }),
  t({ id: 'vocab_guess', mode: 'recognition', graded: true, showTopic: true, tolerance: 'na', response: 'choice', contentType: 'audio' }),
  // Topic names the exact form being tested — the leak §6.14 warns about.
  t({ id: 'conjugation', mode: 'production', graded: true, showTopic: false, tolerance: 'exact', response: 'text', contentType: 'quiz' }),
  t({ id: 'particle_cloze', mode: 'in_context', graded: true, showTopic: false, tolerance: 'exact', response: 'cloze', contentType: 'quiz' }),
  t({ id: 'sentence_scramble', mode: 'in_context', graded: true, showTopic: true, tolerance: 'na', response: 'ordering', contentType: 'quiz' }),
  t({ id: 'grammar_recognition', mode: 'recognition', graded: true, showTopic: false, tolerance: 'na', response: 'choice', contentType: 'quiz' }),
  t({ id: 'grammar_production', mode: 'production', graded: true, showTopic: false, tolerance: 'tolerant', response: 'text', contentType: 'quiz' }),
  t({ id: 'transcription', mode: 'in_context', graded: true, showTopic: true, tolerance: 'exact', response: 'text', contentType: 'audio' }),
  t({ id: 'kanji_writing', mode: 'production', graded: true, showTopic: false, tolerance: 'na', response: 'handwriting', contentType: 'quiz', arguable: true }),
]

/* ── Ungraded — academic (14) ────────────────────────────────────────
 * All in_context. All scroll rather than using the frame; all show the
 * topic, because nothing is being recalled and so nothing can be cued. */

const UNGRADED_IDS: Array<[string, ContentType]> = [
  ['text', 'text'],
  ['summary', 'summary'],
  ['topic_card', 'summary'],
  ['diagram_schematic', 'text'],
  ['input_output_balance', 'text'],
  ['stat_boxes', 'text'],
  ['key_value_pairs', 'text'],
  ['timeline', 'text'],
  ['common_mistakes', 'text'],
  ['comparison_vs_similar', 'text'],
  ['formula_equation', 'text'],
  ['hero_image', 'text'],
  ['globe_pin', 'text'],
  ['model_3d', 'video'],
]

const UNGRADED: ModuleTypeSpec[] = UNGRADED_IDS.map(([id, contentType]) =>
  t({ id, mode: 'in_context', graded: false, showTopic: true, tolerance: 'na', response: 'scroll', contentType }),
)

export const MODULE_TYPES: ModuleTypeSpec[] = [
  ...GRADED_ACADEMIC,
  ...GRADED_LANGUAGE,
  ...UNGRADED,
]

const BY_ID = new Map(MODULE_TYPES.map((m) => [m.id, m]))

export function moduleType(id: string): ModuleTypeSpec | undefined {
  return BY_ID.get(id)
}

/** Falls back to the ungraded scroll shape — an unknown type must never
 *  crash a session (§13.5 error boundaries). */
export function moduleTypeOrDefault(id: string): ModuleTypeSpec {
  return (
    BY_ID.get(id) ?? {
      id,
      mode: 'in_context',
      graded: false,
      showTopic: true,
      tolerance: 'na',
      response: 'scroll',
      contentType: 'text',
    }
  )
}

export const CONTENT_TYPES: ContentType[] = [
  'summary',
  'text',
  'video',
  'audio',
  'flashcard',
  'quiz',
]

/** §3.2: the frontend colours by ContentType and nothing else. */
export function accentVar(c: ContentType): string {
  return `var(--accent-${c})`
}
